src/Microsoft.Azure.Functions.PowerShellWorker.csproj
test/Microsoft.Azure.Functions.PowerShellWorker.Test.csproj

Update sdk to release

---

NuGet.config

@pragnagopa has asked that we add these other nuget feeds to our nuget.config to be consistent with the other repos.

add other package sources to nuget.config

---

README.md

We had the wrong build steps in the readme. I'm going to merge this in since it's better than the wrong steps that are there now but feel free to drop comments and I'll address them later.

correct the build steps

---

test/Modules/Microsoft.Azure.Functions.PowerShellWorker.Tests.ps1

Update the module tests to not depend on the internal data structure.

Update the module tests to not depend on internal data structure

---

src/Logging/RpcLogger.cs

Fix the logging to make logs more readable.

Fix the logging to make logs more readable

---

src/Microsoft.Azure.Functions.PowerShellWorker.csproj
src/Utility/TypeExtensions.cs
test/Microsoft.Azure.Functions.PowerShellWorker.Test.csproj

Update worker to build against 6.2.0-preview.2 SDK

Update worker to build against 6.2.0-preview.2 SDK

---

src/FunctionLoader.cs
test/Unit/PowerShell/PowerShellManagerTests.cs

Adding latest Az PowerShell modules path to PSModulePath for private preview of managed dependency feature for Az Modules.

Adding latest AzPSModulesPath to PSModulePath for private preview

---

.gitignore
tools/helper.psm1

Update 'New-gRPCAutoGenCode' to recursively find all .proto files and generate C# files for all of them.
Also, move all generated gRPC files to `src/Messaging/gRPC`.

Update 'New-gRPCAutoGenCode' to recursively find all .proto files

---

protobuf/src/proto/FunctionRpc.proto
protobuf/src/proto/identity/ClaimsIdentityRpc.proto
protobuf/src/proto/shared/NullableString.proto
src/Microsoft.Azure.Functions.PowerShellWorker.csproj

Updated proto files used by the PowerShell worker.
* Updated subtree from https://github.com/azure/azure-functions-language-worker-protobuf. Branch: dev . Commit:2e9cf4b.
* Updated project to use Grpc.Core version 1.19.0

Updated proto files used by the PowerShell worker.

---

src/Modules/Microsoft.Azure.Functions.PowerShellWorker/Microsoft.Azure.Functions.PowerShellWorker.psm1
src/Modules/Microsoft.Azure.Functions.PowerShellWorker/PowerShellWorker.Resource.psd1
test/Unit/Modules/Microsoft.Azure.Functions.PowerShellWorker.Tests.ps1
test/Unit/PowerShell/PowerShellManagerTests.cs

Enhance Push-OutputBinding by using the output binding information.

Enhance Push-OutputBinding by using the output binding information

---

src/Microsoft.Azure.Functions.PowerShellWorker.csproj
test/Unit/Microsoft.Azure.Functions.PowerShellWorker.Test.csproj

Rev PowerShell SDK version

---

src/Utility/TypeExtensions.cs
test/Unit/Utility/TypeExtensionsTests.cs

Treat the string TypeData as Json if possible.
Will add test tomorrow.

Treat the string TypeData as Json if possible

---

build.ps1
test/Unit/Microsoft.Azure.Functions.PowerShellWorker.Test.csproj

Minor cleanup changes to build.ps1 and test .csproj file

Minor cleanup changes to build.ps1 and test .csproj file

---

src/Public/HttpContext.cs
src/Utility/TypeExtensions.cs
test/Unit/Utility/TypeExtensionsTests.cs

Fixed issue https://github.com/Azure/azure-functions-powershell-worker/issues/207

Set response Content-Type to 'application/json' when an object is provided to Body

---

test/Unit/DependencyManagement/DependencyManagementTests.cs

Fixing test pass.

---

src/DependencyManagement/DependencyManager.cs
src/DependencyManagement/DependencySnapshotPurger.cs
src/PowerShell/PowerShellManagerPool.cs
src/Utility/PowerShellWorkerConfiguration.cs

Refactoring: Retrieve all PSWorker config values via PowerShellWorkerConfiguration

Refactoring: Retrieve all PSWorker config values via PowerShellWorkerConfiguration

---

src/Microsoft.Azure.Functions.PowerShellWorker.csproj
test/Unit/Microsoft.Azure.Functions.PowerShellWorker.Test.csproj

We need to add you folks to our partner alias so you know when we release patch versions.
This revs the versions of the PowerShell SDK

Update to 6.2.2

---

docs/designs/PowerShell-AzF-Overall-Design.md
protobuf/README.md
protobuf/src/proto/FunctionRpc.proto
protobuf/src/proto/identity/ClaimsIdentityRpc.proto
protobuf/src/proto/shared/NullableTypes.proto
src/FunctionInfo.cs
src/PowerShell/PowerShellManager.cs
src/Public/TraceContext.cs
src/RequestProcessor.cs
test/Unit/PowerShell/PowerShellManagerTests.cs

Part of fix for https://github.com/Azure/azure-functions-host/issues/3747

Adding TraceContext as parameter

---

src/DependencyManagement/DependencyManager.cs
src/DependencyManagement/DependencySnapshotInstaller.cs
src/resources/PowerShellWorkerStrings.resx
test/Unit/DependencyManagement/DependencyManagementTests.cs
test/Unit/DependencyManagement/DependencyManagerTests.cs
test/Unit/DependencyManagement/DependencyManifestTests.cs
test/Unit/PowerShell/PowerShellManagerTests.cs

Fixing typos, replacing"FunctionApp" with "function app", etc.

Fix log messages

---

src/Messaging/MessagingStream.cs
src/Worker.cs

Apply the grpcMaxMessageLength setting received from the host to configure the gRPC channel
