Azure/azure-functions-powershell-worker

package/Microsoft.Azure.Functions.PowerShellWorker.Package.csproj, package/Microsoft.Azure.Functions.PowerShellWorker.nuspec
For the Deploy to work in AppVeyor, we need to set the build number to the patch version.
@pragnagopa has asked that the version generated be in the following format:
0.1.BUILD_NUMBER-alpha
=> set build number in CI

NuGet.config
Remove `powershell-core` feed from NuGet.config.
I think it's OK to remove it, but will wait on the CIs.
=> Remove `powershell-core` feed from NuGet.config

build.ps1, examples/PSCoreApp/GetAzureVmHttpTrigger/run.ps1, src/PowerShell/PowerShellManager.cs, src/requirements.psd1
Az is the future. This uses that and changes the cmdlet we use.
fixes #48
=> switch to the Az module for Azure

src/FunctionLoader.cs, src/PowerShell/PowerShellExtensions.cs, src/PowerShell/PowerShellManager.cs, src/RequestProcessor.cs, src/Utility/TypeExtensions.cs, test/PowerShell/PowerShellManagerTests.cs, test/Utility/TypeExtensionsTests.cs
Fix #71 
- Use `ConvertTo-Json` for converting the results returned from the function to JSON. So objects that are wrapped in `PSObject` won't be a problem anymore.
- Refactor the code to make it ready for durable function implementation.
The implementation of invoking an orchestration function is made a placeholder in this PR, where it throws `NotImplementedException` when an orchestration function is triggered.
See `RequestProcessor.InvokeOrchestrationFunction`.
=> Bug fixes and code refactoring to get it ready for durable function support

src/PowerShell/PowerShellManager.cs, src/Utility/TypeExtensions.cs
When the return/output object is a complex one, the powershell worker will freeze when converting it to JSON due to `-Depth 10` in the call to `ConvertTo-Json`. Talked to @eamonoreilly and decided to change to 3, which should be deep enough for most real scenarios.
=> Update JSON conversion depth to 3 to get better responsiveness given a complex return object

src/Utility/TypeExtensions.cs, test/Utility/TypeExtensionsTests.cs
There are 2 changes here:
1. Use 'JsonObject.ConvertFromJson' to serialize JSON binding input. We have to use reflection because the reference assemblies are missing in our SDK NuGet packages.
2. Check for `PSObject` in our `ToTypedData` method, so that it handles wrapped objects properly.
=> Use 'JsonObject.ConvertFromJson' to serialize JSON binding input

src/PowerShell/PowerShellManager.cs
As the name implies, this removes `$returns` support unless a user uses `Push-OutputBinding` to push to `$returns`.
We will probably bring this back in the future, but we want to receive feedback in #82 before we pick a direction.
=> remove $returns support for now

src/requirements.psd1
Because we are unable to override where Install-Module goes, we are removing PowerShellGet for now until we get some feedback.
If a user wants to use it for `Save-*` or `Publish-*` they can bring it in just like any other module.
=> remove powershellget from worker

README.md, src/PowerShell/PowerShellExtensions.cs, src/PowerShell/PowerShellManager.cs, test/Unit/PowerShell/PowerShellExtensionsTests.cs
Before, we didn't have the `isUserLog: true` property when we were logging things from the pipeline which means they only showed up as system logs. This is fixed in this PR.
However, we were also using a naive `ToString()` this has been replaced with a similar script:
```powershell
Write-Output $obj | Out-String
```
=> Log items added to the pipeline

src/Http/HttpResponseContext.cs, src/Utility/TypeExtensions.cs, test/E2E/HttpTrigger.Tests.ps1, test/E2E/TestFunctionApp/TestBasicHttpTrigger/run.ps1, test/E2E/TestFunctionApp/TestBasicHttpTriggerWithTriggerMetadata/run.ps1, test/Unit/Utility/TypeExtensionsTests.cs
Change the type of 'StatusCode' to 'System.Net.HttpStatusCode', so that it can accept status code in the form of integer, string, and enum 'HttpStatusCode'.
=> Make 'StatusCode' accept status code in the form of integer, string, and enum

src/PowerShell/PowerShellManager.cs, src/RequestProcessor.cs, src/requirements.psd1, test/Unit/PowerShell/PowerShellManagerTests.cs
Sending this as a new PR as I wanted to rework some things...
This PR:
* Removes the Az module from the worker - if the user wants to interact with Azure, they should do:
```powershell
Save-Module Az.Profile ./Modules
Save-Module Az.KeyVault ./Modules
```
from their Function App root.
Also... if the user has enabled MSI and Az.Profile is available, we auto-authenticate to Azure. We also attempt to auth via Service Principal if they have the required environment variables.
=> remove az dependency and add MSI support

src/PowerShell/PowerShellManager.cs
@joeyaiello @TylerLeonhardt We agreed on removing Service Principle support, right?
=> Remove Service Principal support

.vscode/tasks.json, examples/PSCoreApp/Profile.ps1, src/FunctionLoader.cs, src/PowerShell/PowerShellManager.cs, src/RequestProcessor.cs, test/E2E/HttpTrigger.Tests.ps1, test/E2E/TestFunctionApp/Profile.ps1, test/E2E/TestFunctionApp/TestBasicHttpTriggerWithProfile/function.json, test/E2E/TestFunctionApp/TestBasicHttpTriggerWithProfile/run.ps1, test/E2E/setupE2Etests.ps1, test/Microsoft.Azure.Functions.PowerShellWorker.Test.csproj, test/Unit/Function/FunctionLoaderTests.cs, test/Unit/PowerShell/PowerShellManagerTests.cs, test/Unit/PowerShell/TestScripts/ProfileBasic/profile.ps1, test/Unit/PowerShell/TestScripts/ProfileWithNonTerminatingError/Profile.ps1, test/Unit/PowerShell/TestScripts/ProfileWithTerminatingError/profile.ps1
This allows you to put a `Profile.ps1` in your Function App root that will be run at every COLD START of your Function App. Please refer to the empty `example/PSCoreApp/Profile.ps1` for usecases.
fixes #110
=> Profile.ps1 support and removal of auto-auth to azure

src/FunctionLoader.cs, src/PowerShell/PowerShellManager.cs, src/PowerShell/PowerShellManagerPool.cs, src/Public/FunctionMetadata.cs, src/RequestProcessor.cs, test/Unit/PowerShell/PowerShellManagerTests.cs, test/Unit/Utility/TypeExtensionsTests.cs
Refactor the code base to make it easy to support concurrency within a worker in future.
- Add `PowerShellManagerPool` , but it's just the skeleton. Today the pool only has one PowerShellManager instance. We can add the real pool implementation if we decide to support concurrency within a worker process.
- Setup the `PSModule` environment variable as part of `Runspace.Open` by using `InitialSessionState.EnvironmentVariables`. This fixes the mysterious `ModulePathShouldBeSetCorrectly` test failure by making sure the env variable is set to the expected one as part of the `Runspace.Open` of every `PowerShellManager`. It failed before because:
1. `dotnet test` runs tests in parallel by default
1. when creating a new `PowerShellManager`, the `PSModulePath` environment variable will be set …
=> Refactor the code base to make it easy to support concurrency within a worker in future

test/Unit/Modules/Microsoft.Azure.Functions.PowerShellWorker.Tests.ps1
Formatting tables is different in pwsh 6.2-preview.3. We can no longer be sure that the last 2 items in a format-table string are new lines.
Now we walk backwards until we hit the last not whitespace line.
=> fix test failure on pwsh 6.2-preview.3

build.ps1, package/Microsoft.Azure.Functions.PowerShellWorker.nuspec, src/Microsoft.Azure.Functions.PowerShellWorker.csproj, test/Microsoft.Azure.Functions.PowerShellWorker.Test.csproj, tools/helper.psm1
Today, the PowerShell SDK does not lay out the modules in such a way that is easily importable by PSModulePath.
Until that day, we will simply bundle the `psd1`s of the `Microsoft.PowerShell.Utility` and `Microsoft.PowerShell.Management` modules with the worker.
In addition to that change, we need to also upgrade to preview3 for Enter-PSHostProcess to work on Unix. This required updating our version of `Newtonsoft.Json` since PowerShell SDK relies on `12.0.1`.
This PR also contains a tiny fix to the nuspec so that it builds the package without error - the `licenseUrl` field is deprecated in favor of the `license` field.
=> Enter-PSHostProcess workaround

package/Microsoft.Azure.Functions.PowerShellWorker.Package.csproj, src/Microsoft.Azure.Functions.PowerShellWorker.csproj, test/E2E/setupE2Etests.ps1, test/Microsoft.Azure.Functions.PowerShellWorker.Test.csproj, tools/helper.psm1
Build against dotnet SDK 2.2. The latest Azure-Function-Host is being built against dotnet 2.2 now.
=> Build against dotnet SDK 2.2

src/Utility/TypeExtensions.cs, test/E2E/HttpTrigger.Tests.ps1
Fix #137
Cast the Hashtable returned from `JsonObject.CovnertFromJson` to a case-insensitive Hashtable as long as it's doable.
If the cast fails, because of keys differ only in case, then we use the original case-sensitive Hashtable.
=> Make the Hashtable returned from ConvertFromJson case-insensitive as long as possible

src/PowerShell/PowerShellManager.cs, src/RequestProcessor.cs, src/Utility/TypeExtensions.cs, test/Unit/Utility/TypeExtensionsTests.cs
`JsonObject.ConvertToJson` API was added in preview.4. The reference assembly for `Microsoft.PowerShell.Commands.Utility.dll` was also added in the SDK nuget package for preview.4, so we can use `JsonObject.ConvertFromJson` and `JsonObject.ConvertToJson` directly.
=> Use ConvertFromJson/ConvertToJson APIs directly

.gitignore, protobuf/README.md, protobuf/src/proto/FunctionRpc.proto, protobuf/src/proto/identity/ClaimsIdentityRpc.proto, tools/helper.psm1
Update the protobuf in the worker repo and also update 'New-gRPCAutoGenCode' accordingly.
- The `dataType` field was added to `BindingInfo` type which reflects the type of the incoming blob content. We can use that info now for pre-validation.
- `FunctionEnvironmentReloadRequest` and `FunctionEnvironmentReloadResponse` were added. We need to review all the supported requests and responses in the protocol, to see if we should support them in PS worker.
- `RpcClaimsIdentity` was added to `RpcHttp`, we need to add the translation logic to convert information from it to `ClaimsPrincipal` or `ClaimsIdentity` (need to look into it closely).
=> Update the protobuf in the worker repo and also update 'New-gRPCAutoGenCode' accordingly

README.md
The status badges we are currently pointing to [`Azure/azure-webjobs-sdk-extensions`](https://github.com/Azure/azure-webjobs-sdk-extensions).
Take a look at the raw text of the `README.md` of that repo, you will see the exact URLs for build status badges.
```
https://ci.appveyor.com/api/projects/status/5mqrok4j3l89cnvx/branch/master?svg=true
https://ci.appveyor.com/api/projects/status/5mqrok4j3l89cnvx/branch/dev?svg=true
```
I changed the URL based on the answer from this thread: https://help.appveyor.com/discussions/questions/471-infer-badge-url-from-github-user-repo-name
=> Update the status badges to point to the right URL

src/RequestProcessor.cs, tools/helper.psm1
Note: I marked this as a draft PR.
fixes #154 
Rather than using a `switch` for handling requests, I've changed it to a Dictionary of handles.
I've implemented all requests... some return responses, others do not.
The worker won't crash now if it receives a message it doesn't understand.
Things I was thinking about:
* maybe 2 dictionaries - 1 for requests (that return a message), 1 for "notifications" (that don't return a message)
* Not sure this PR needs tests with it... I would think we would just test what those Process methods will do
=> No ops for other messages

README.md, src/Microsoft.Azure.Functions.PowerShellWorker.csproj, src/RequestProcessor.cs, src/resources/PowerShellWorkerStrings.resx, test/Unit/Microsoft.Azure.Functions.PowerShellWorker.Test.csproj
Here's an example of what the log looks like:
```
[3/8/19 1:39:09 AM] System Log: {
[3/8/19 1:39:09 AM]   Log-Message: Custom pipe name specified. You can attach to the process by using vscode or by running `Enter-PSHostProcess -CustomPipeName fooooooooood`
[3/8/19 1:39:09 AM] }
```
All you have to do is:
```
PS /MyFuncApp/ > $env:PSWorkerCustomPipeName = "helloworldfunc"
PS /MyFuncApp/ > func start
```
I've tested that this works along with [this vscode-powershell PR](https://github.com/powerShell/vscode-powershell/pull/1775) where you hit F5 and the debugger attaches to the correct runspace.
also a tiny README change
=> Move to rc.1 and support the CustomPipe

build.ps1, src/PowerShell/PowerShellManager.cs, src/PowerShell/PowerShellManagerPool.cs, src/Public/FunctionMetadata.cs, test/Unit/PowerShell/PowerShellManagerTests.cs
Bring back the code that was removed in #134. The post-invocation data transformation was moved from the helper module to the worker in that PR, and that makes this code useless at that moment.
When script from the helper module is running, it can use `[FuncMetadata]::GetOutputBindingInfo([Runspace]::DefaultRunspace.InstanceId)` to get the output binding info about the function that is currently running. Hence, `Push-OutputBinidng` can do smart things based on the `-Name`.
=> Bring back the code that shares output binding metadata with the helper module

src/Microsoft.Azure.Functions.PowerShellWorker.csproj
Quoted from https://devblogs.microsoft.com/dotnet/tiered-compilation-preview-in-net-core-2-1/
> In our testing, time spent jitting would often decrease by about 35%.
Enable tiered compilation for the worker to help the code start.
=> Enable tiered compilation for the worker to help the code start

src/Logging/RpcLogger.cs, src/PowerShell/PowerShellManager.cs, src/PowerShell/PowerShellManagerPool.cs, src/RequestProcessor.cs, src/resources/PowerShellWorkerStrings.resx, test/Unit/PowerShell/PowerShellManagerTests.cs
Avoid creating RpcLogger instances unnecessarily by adding static method 'WriteSystemLog' to RpcLogger.
Also add two more system logging messages in the pool:
- log about the pool upper bound
- log when a new PowerShell manager instance is added to the pool.
=> Avoid creating RpcLogger instances unnecessarily by adding static method 'WriteSystemLog' to RpcLogger

src/DependencyManagement/DependencyManager.cs, src/PowerShell/PowerShellManager.cs, src/Utility/Utils.cs
- Use cached `CmdletInfo` object for `Import-Module`, `Remove-Module`, `Start-Job` and `Remove-Job` to avoid the command lookup time.
- Clean up jobs started during the function execution
=> Clean up jobs started during the function execution

src/PowerShell/PowerShellManagerPool.cs
Fix the pool size log to reflect the correct size when the env variable is not set
=> Fix the pool size log to reflect the correct size when the env variable is not set

build.ps1, docs/cmdlets/Get-OutputBinding.md, docs/cmdlets/Push-OutputBinding.md, docs/cmdlets/Trace-PipelineObject.md, src/Modules/Microsoft.Azure.Functions.PowerShellWorker/Microsoft.Azure.Functions.PowerShellWorker.psm1
`SupportsWildcards` is what PlatyPS uses to set the field in the help.
Also, the PlatyPS test wasn't actually running the help because the module wasn't imported. This fixes that.
=> Add SupportsWildcards to Get-OutputBinding and fix help test

src/FunctionInfo.cs, test/Unit/Modules/Microsoft.Azure.Functions.PowerShellWorker.Tests.ps1
Make the binding-info dictionary case-insensitive on the key (binding name).
When testing the bindings in our priority list, I found currently `Push-OutputBinding` treat the output binding name case-sensitively.
If the output binding name in `function.json` is `outblob`, then `Push-OutputBinding -Name outBlob` will fail. This PR fixes that issue.
=> Make the binding-info dictionary case-insensitive on the key (binding name)

src/FunctionInfo.cs, src/PowerShell/PowerShellManager.cs, src/RequestProcessor.cs, test/E2E/Azure.Functions.PowerShellWorker.E2E/Azure.Functions.PowerShellWorker.E2E/HttpEndToEndTests.cs, test/E2E/TestFunctionApp/HttpTriggerWithMetadata/function.json, test/E2E/TestFunctionApp/HttpTriggerWithMetadata/run.ps1
Fix #187
Add `InvocationId`, `FunctionDirectory` and `FunctionName` to `$TriggerMetadata` to make it consistent with the Python worker.
Also, construct the `TriggerMetadata` value only if it's specified.
=> Add 'InvocationId', 'FunctionDirectory' and 'FunctionName' to $TriggerMetadata

src/Messaging/MessagingStream.cs, src/PowerShell/PowerShellManager.cs, src/PowerShell/PowerShellManagerPool.cs, src/RequestProcessor.cs
Look, I have been trying to figure out what is dragging the throughput of the PowerShell worker, and I believe synchronization is the root cause.
The following screenshot is the concurrency view of the PowerShell worker when running under throughput test.
The throughput test simulates 100 users for 100 seconds, each sends an HTTP trigger request every 1-3 seconds. The response from PS function is a simple 'OK' status.
Both the function host process and the worker process are configured with 1-core processor affinity, to mimic the sandbox environment.
The concurrency level of the PowerShell worker is configured to 1, meaning only one invocation request can be handled at a time. This is the default configuration.
As we can see, threads spend 97% of their time on synchronization, and only 1% …
=> Improve throughput ... a bit

src/DependencyManagement/DependencyManager.cs, test/Unit/DependencyManagement/DependencyManagementTests.cs
Updating Managed Dependencies folder installation path for local development.
In the PowerShell worker, for local development, we install the function app dependencies (ManagedDependencies) under the function app root. However, when this happens, the Process Host gets restarted (since new files were added to the function app root). This causes the CLI to go into an infinite loop. This doesn’t happen in the cloud because we install the function app dependencies under home/data/ManagedDependencies.
=> Updating Managed Dependencies folder installation path for local development.

src/DependencyManagement/DependencyManager.cs, src/PowerShell/PowerShellManager.cs, src/PowerShell/PowerShellManagerPool.cs, src/RequestProcessor.cs, src/resources/PowerShellWorkerStrings.resx
This PR has the changes to download managed dependency on a background thread and show the managed dependency download in progress message on the azure portal and on the CLI console when a function invocation is triggered while managed dependency download is in-progress
=> Managed dependency download on background thread

src/DependencyManagement/DependencyManager.cs, src/PowerShell/PowerShellManager.cs, src/RequestProcessor.cs, src/Utility/Utils.cs
Refactor and clean up the code base based on the dependency management changes.
- Reduce redundant code -- `initialsessionstate` creation and failure response in `FunctionLoad` processing
- Remove the unnecessary `_powershellPool.ReclaimUsedWorker(psManager);` in `ProcessInvocationRequest`.
- Change the line ending from `CRLF` to `LF` in `Utils.cs`.
- It's easier to review with https://github.com/Azure/azure-functions-powershell-worker/pull/194/files?w=1
=> Refactor and clean up based on the dependency management changes

src/Microsoft.Azure.Functions.PowerShellWorker.csproj
Address #197 
Rev the gRPC/protobuf nuget package version.
We probably should enable [`dependabot`](https://github.com/PowerShell/PowerShell/pull/9264) for this repository.
=> Rev the gRPC/protobuf nuget package version

src/Utility/TypeExtensions.cs, test/Unit/Utility/TypeExtensionsTests.cs
Fix #205
Special case `RpcHttp.RawBody` field to always return the literal string.
NodeJS worker does the same for `RawBody`: https://github.com/Azure/azure-functions-nodejs-worker/blob/dev/src/Converters.ts#L18
=> Special case the 'RpcHttp.RawBody' field to always return the literal string

src/DependencyManagement/DependencyManager.cs, src/PowerShell/PowerShellManager.cs, src/PowerShell/PowerShellManagerPool.cs, src/RequestProcessor.cs, src/Utility/Utils.cs, src/resources/PowerShellWorkerStrings.resx, test/Unit/PowerShell/PowerShellManagerTests.cs
This is to fix the regression in local debugging.
We create the first `PowerShellManager` instance when processing the first `FunctionLoad` request, so the debugger has the target Runspace to attach to.
However, we delay the initialization of the first `PowerShellManager` instance until the first invocation (when checking out the instance from pool).
It turns out we cannot have the dependency manager to create a separate Runspace for downloading.
The VS Code local debugging assumes the target `Runspace` has `Id = 1`, which was true before as only one Runspace will be created initially.
Now, the dependency manager creates a separate `Runspace` for downloading, and there will be a race condition -- sometimes the `Runspace` created for the downloading has `Id = 1`, and thus the debugger will …
=> Create the first PowerShellManager instance when processing the first FunctionLoad request

src/DependencyManagement/DependencyManager.cs, src/resources/PowerShellWorkerStrings.resx
This PR addresses issue https://github.com/Azure/azure-functions-powershell-worker/issues/218.
Changes in this PR:
* Adding function app dependencies installation retry logic with exponential back off. If an issue is encountered. We retry a maximum of 3 times, and we wait in between tries 1, 2, 4 seconds, respectively. 
* Before we installed the function app dependencies, we need to ensure that the user has write access to their storage account. To validate this, we create the module destination path if it does not exist, and if it exists, we try to empty it. If an issue is encountered, we error out and advice to user to ensure that they have write access to the path where the dependencies will be installed. 
* Updated error messages to keep consistency.
=> Adding function app dependencies installation retry logic with exponential back off.

protobuf/README.md, protobuf/src/proto/FunctionRpc.proto, protobuf/src/proto/identity/ClaimsIdentityRpc.proto, protobuf/src/proto/shared/NullableString.proto, protobuf/src/proto/shared/NullableTypes.proto
This PR contains the following change:
* Updated subtree from https://github.com/azure/azure-functions-language-worker-protobuf. Tag: v1.2.0-protofile. Commit: 77b0401b85b6bf89494f0fab2313a336fcacb41f
=> Update proto files used by the PowerShell worker. 

src/RequestProcessor.cs
For some reason, we receive a `FunctionLoadRequest` for when a proxy is configured. Proxies don't have the `Metadata.Directory` set which caused initialization issues with the `PSModulePath`. The only way to tell if a `FunctionLoadRequest` is from a proxy is to test if `Metadata.Directory` is `null` or empty.
That is what this PR does.
I discovered this on my Twitch stream when I tried to run my [PSScriptAnalyzer as a service](https://pssafuncapp.azurewebsites.net) function app and it complained while debugging that PSScriptAnalyzer wasn't in any module path because the FunctionApp level module path was not appended to the `PSModulePath` properly.
This behavior did change because this Function App use to work with a proxy configured, but now it does not... so I'm not sure if the host …
=> Fix issue with proxies

test/E2E/Azure.Functions.PowerShellWorker.E2E/Azure.Functions.PowerShellWorker.E2E/ManagedDependenciesEndToEndTests.cs
Allow both '/' and '\' in module path
=> Fix E2E test on Linux: allow both '/' and '\' in module path

src/FunctionLoader.cs, src/RequestProcessor.cs
This mitigates issue https://github.com/Azure/azure-functions-powershell-worker/issues/276.
The PowerShell worker seems to be relying on a guarantee that has never been explicitly provided by the Azure Functions host. Recently, the PowerShell worker started receiving more than one function load request with the same FunctionId. Apparently, this is caused by a change on the Azure Functions host side, and the root cause and the overall effect of this change are still to be investigated. In the meantime, we want to let the PowerShell worker tolerate this situation, which will make the load request operation idempotent.
=> Ignore function load requests with duplicate FunctionId values

src/PowerShell/PowerShellManager.cs
Fixed issue:
If a PowerShell function invokes Push-OutputBinding and then throws an exception, the next invocation response contains data passed to Push-OutputBinding on the previous invocation.
=> Clear pushed output binding values on exceptions

src/FunctionLoader.cs, src/RequestProcessor.cs
Cherry-picking https://github.com/Azure/azure-functions-powershell-worker/pull/278 fix from the dev branch in order to hotfix the https://github.com/Azure/azure-functions-powershell-worker/issues/276 issue.
* Add FunctionLoader IsLoaded method
* Return from ProcessFunctionLoadRequest early if already loaded
=> Ignore function load requests with duplicate FunctionId values (#278)

src/DependencyManagement/DependencyManager.cs, src/DependencyManagement/DependencySnapshotInstaller.cs, src/DependencyManagement/IDependencySnapshotInstaller.cs, test/Unit/DependencyManagement/DependencyManagerTests.cs, test/Unit/DependencyManagement/DependencySnapshotInstallerTests.cs
Refactoring: moving GetModuleLatestPublishedVersion method from DependencyManager to DependencySnapshotInstaller. This simplifies the overall structure and makes DependencyManager unit tests cleaner.
=> Move GetModuleLatestPublishedVersion from DependencyManager to DependencySnapshotInstaller

src/DependencyManagement/DependencyManager.cs, src/DependencyManagement/DependencySnapshotInstaller.cs, src/DependencyManagement/DependencySnapshotPurger.cs, src/Logging/ILogger.cs, src/Logging/RpcLogger.cs, src/PowerShell/PowerShellManager.cs, src/PowerShell/PowerShellManagerPool.cs, src/PowerShell/StreamHandler.cs, src/RequestProcessor.cs, test/Unit/DependencyManagement/DependencyManagerTests.cs, test/Unit/DependencyManagement/DependencySnapshotPurgerTests.cs, test/Unit/Logging/ConsoleLogger.cs
Logging fixes:
- In order to make the separation between user-only logs and internal service logs very explicit, the `isUserLog` parameter is renamed to `isUserOnlyLog`, moved to the front, and made mandatory.
- Most managed dependencies logs are switched to `isUserOnlyLog: false`. As a result, the logs written by the background task will not be lost anymore, and they will now be available to both the users and the service engineers.
- `RpcLogger.WriteSystemLog` used to write the log message as three separate lines, and only the first line had the required `LanguageWorkerConsoleLog` prefix. As a result, the main part of the log message was not sent to the service logs. Fixed by merging the message into a single line.
- Sharing a single `StringBuilder` instance between `Log` calls was not …
=> Logging fixes

src/DependencyManagement/PowerShellGalleryModuleProvider.cs
If a module on the PowerShell gallery has both regular and prerelease versions present within the same major version (for example, both `2.1` and `2.2-alpha4` are present), and `requirements.psd1` specifies `'MyModule' = '2.*'`, the PowerShell worker does not handle this situation very well.
From the user perspective, any of the following options would make some sense:
1. Install the latest version even if it is a prerelease version (`2.2-alpha4` in this example).
2. Install the latest version excluding prerelease versions (`2.1` in this example).
3. Make it possible for the user to express the intent, perhaps by providing the module version specification in `requirements.psd1` accordingly.
What actually happens is different from any of these options: the PowerShell worker chooses …
=> Managed Dependencies: Ignore prerelease module versions

src/DependencyManagement/DependencySnapshotInstaller.cs, src/resources/PowerShellWorkerStrings.resx, test/Unit/DependencyManagement/DependencyManagementTests.cs, test/Unit/DependencyManagement/DependencySnapshotInstallerTests.cs
If installing a managed dependencies snapshot fails for any reason, the current code just abandons the snapshot folder, relying on it to be eventually removed by regular purge. As a result, the partially installed snapshot keeps occupying file space, and prevents the next installation attempt from starting soon. There is no easy way to avoid these consequences when the PowerShell worker process is terminated. However, if the worker keeps running and it is aware of the installation attempt failure, it has an opportunity to perform the clean up sooner. This is what this PR achieves.
=> Remove partially installed snapshots

docs/designs/PowerShell-AzF-Overall-Design.md, src/DependencyManagement/DependencyInfo.cs, src/DependencyManagement/DependencyManagerStorage.cs, src/DependencyManagement/DependencyManifest.cs, src/DependencyManagement/DependencyManifestEntry.cs, src/DependencyManagement/DependencySnapshotInstaller.cs, src/DependencyManagement/IDependencyManagerStorage.cs, src/DependencyManagement/InstalledDependenciesLocator.cs, src/DependencyManagement/PowerShellGalleryModuleProvider.cs, src/DependencyManagement/VersionSpecificationType.cs, src/resources/PowerShellWorkerStrings.resx, test/Unit/DependencyManagement/DependencyManagementTests.cs, test/Unit/DependencyManagement/DependencyManagerTests.cs, test/Unit/DependencyManagement/DependencyManifestTests.cs, test/Unit/DependencyManagement/DependencySnapshotInstallerTests.cs, test/Unit/DependencyManagement/InstalledDependenciesLocatorTests.cs
Allow specifying exact module versions in `requirements.psd1`, in addition to the `<MajorVersion>.*` pattern. Addressing https://github.com/Azure/azure-functions-powershell-worker/issues/256.
=> Allow exact module versions in requirements.psd1

src/DependencyManagement/IPowerShellGallerySearchInvoker.cs, src/DependencyManagement/PowerShellGalleryModuleProvider.cs, src/DependencyManagement/PowerShellGallerySearchInvoker.cs, test/Unit/DependencyManagement/PowerShellGalleryModuleProviderTests.cs
When a module on the PowerShell Gallery contains many (100+) versions, PowerShell Gallery API returns a limited number of entries and a link to the next page. Before this fix, PS Worker would process the first page only, failing to detect the latest version correctly in some cases. This fix makes PS Worker request and process all the subsequent pages.
=> Managed Dependencies: handle paginated PSGallery response

src/RequestProcessor.cs, src/Utility/TypeExtensions.cs, test/Unit/Utility/TypeExtensionsTests.cs
Resolving issue https://github.com/Azure/azure-functions-powershell-worker/issues/292.
The goal is to reduce data duplication in function invocation requests, which will reduce the I/O volume between the host and the PS worker, and potentially allow larger request payloads.
=> Implemented "RpcHttpBodyOnly" capability

src/requirements.psd1
Updating module versions to match the versions shipped with PS v6.2.2: https://github.com/PowerShell/PowerShell/blob/v6.2.2/src/Modules/PSGalleryModules.csproj
=> Update module versions to match PS v6.2.2

src/PowerShell/ErrorRecordFormatter.cs, src/PowerShell/PowerShellManager.cs, src/PowerShell/StreamHandler.cs, test/Unit/PowerShell/ErrorRecordFormatterTests.cs, test/Unit/PowerShell/PowerShellManagerTests.cs
Resolves https://github.com/Azure/azure-functions-powershell-worker/issues/145 (see the last proposal).
For example, the following script:
``` PowerShell
$ErrorActionPreference = 'Stop'
function MyFunctionA { 'abc' | ConvertFrom-Json }
function MyFunctionB { MyFunctionA }
MyFunctionB
```
will produce a trace like this:
```
[9/16/2019 7:46:23 PM] EXCEPTION: ConvertFrom-Json : Conversion from JSON failed with error: Unexpected character encountered while parsing value: a. Path '', line 0, position 0.
[9/16/2019 7:46:23 PM] At D:\GitHub\AnatoliB\af-ps-errors\Error\run.ps1:8 char:13
[9/16/2019 7:46:23 PM] +     'abc' | ConvertFrom-Json
[9/16/2019 7:46:23 PM] +             ~~~~~~~~~~~~~~~~
[9/16/2019 7:46:23 PM] + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException …
```
=> Log function script exception and error details

src/Worker.cs, src/resources/PowerShellWorkerStrings.resx
Resolving https://github.com/Azure/azure-functions-powershell-worker/issues/321
=> Log PowerShell Worker version on start

test/Unit/DependencyManagement/DependencySnapshotInstallerTests.cs
"error CS1738: Named argument specifications must appear after all fixed arguments have been specified. Please use language version 7.2 or greater to allow non-trailing named arguments."
=> Fixing error CS1738 in the unit test code

src/PowerShell/PowerShellManager.cs, src/PowerShell/StreamHandler.cs, src/resources/PowerShellWorkerStrings.resx
Log just the fact of encountering CommandNotFoundException without any further detail, for monitoring purposes.
=> Log CommandNotFoundException raised by function code

src/DependencyManagement/BackgroundDependencySnapshotMaintainer.cs, src/DependencyManagement/DependencyManager.cs, src/DependencyManagement/DependencySnapshotInstallationMode.cs, src/DependencyManagement/DependencySnapshotInstaller.cs, src/DependencyManagement/IDependencySnapshotInstaller.cs, src/resources/PowerShellWorkerStrings.resx, test/Unit/DependencyManagement/BackgroundDependencySnapshotMaintainerTests.cs, test/Unit/DependencyManagement/DependencyManagementTests.cs, test/Unit/DependencyManagement/DependencyManagerTests.cs, test/Unit/DependencyManagement/DependencySnapshotInstallerTests.cs
Improve dependency management logs:
- For every dependency snapshot installation start, success, or failure event, log the installation mode as well ("Required" vs. "Optional").
- Log AcceptableFunctionAppDependenciesAlreadyInstalled just once on worker start, no need to repeat it later.
=> Improve dependency management logs
